// Generated by tools/extract-sprites.mjs. Do not edit.
const SPRITE_RECTS = {"front":[1,1,37,42],"side":[39,1,34,42],"three":[74,1,36,42],"back":[111,1,37,42],"wave":[149,1,36,39],"run":[186,1,33,39],"crouch":[220,1,34,33],"jump":[255,1,37,36],"rcFront":[293,1,14,16],"rcSide":[308,1,15,16],"rcBack":[324,1,14,16]};
const SPRITE_FACING = {"front":0,"side":-1,"three":-1,"back":0,"wave":0,"run":1,"crouch":-1,"jump":-1,"rcFront":0,"rcSide":1,"rcBack":0};
